POST http://localhost:8080/contact-us
Content-Type: application/json

{
  "name" : "Mamadou Yaya DIALLO",
  "email" : "yayamombeya090@gmail.com",
  "reason" :  "DEMANDE INFOR",
  "others" : null,
  "comment" : "Need some information, please call me on 622315214"
}
###

#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
###


curl --request POST \
--url https://api.sendgrid.com/v3/mail/send \
--header 'authorization: Bearer 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' \
--header 'content-type: application/json' \
--data '{"personalizations":[{"to":[{"email":"myaya.diallo@wuriguinee.com","name":"John Doe"}],"subject":"Hello, World!"}],"from":{"email":"sam.smith@example.com","name":"Sam Smith"},"reply_to":{"email":"sam.smith@example.com","name":"Sam Smith"}}'
POST https://api.sendgrid.com/v3/mail/send
authorization: Bearer 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
Content-Type: application/json

{
  "personalizations": [
    {
      "to": [
        {
          "email": "myaya.diallo@wuriguinee.com",
          "name": "John Doe"
        }
      ],
      "subject": "Hello, World!"
    }
  ],
  "from": {
    "email": "sam.smith@example.com",
    "name": "Sam Smith"
  },
  "reply_to": {
    "email": "sam.smith@example.com",
    "name": "Sam Smith"
  }
}

###

