#POST https://guinea-sandbox.mosip.net/pre-registration-contactus/contact-us
POST http://localhost:8081/pre-registration-contactus/contact-us
Content-Type:application/json
emailSubject:'Reception de votre demande'
sendGridEmailId:myaya.diallo@wuriguinee.com
sendGridSecretKey:---Change by the given secret id----

{
  "name" : "Mamadou Yaya DIALLO",
  "email" : "yayamombeya090@gmail.com",
  "reason" :  "DEMANDE INFOR",
  "otherReason" : null,
  "message" : "Need some information, please call me on 622315214"
}

###
